/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SocialLeadsRouteImport } from './routes/social-leads'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveDemoRouteImport } from './routes/live-demo'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as ExecutiveDashboardRouteImport } from './routes/executive-dashboard'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as BotFlowRouteImport } from './routes/bot-flow'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as AiSummaryRouteImport } from './routes/ai-summary'
import { Route as AiIntelligenceRouteImport } from './routes/ai-intelligence'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WhatsappFlowsIndexRouteImport } from './routes/whatsapp-flows.index'
import { Route as BotTreeIndexRouteImport } from './routes/bot-tree.index'
import { Route as WhatsappFlowsNewRouteImport } from './routes/whatsapp-flows.new'
import { Route as WhatsappFlowsIdRouteImport } from './routes/whatsapp-flows.$id'
import { Route as FlowBuilderIdRouteImport } from './routes/flow-builder.$id'
import { Route as BotTreeIdRouteImport } from './routes/bot-tree.$id'
import { Route as TammulRouteImport } from './routes/tammul'

const TammulRoute = TammulRouteImport.update({
  id: '/tammul',
  path: '/tammul',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialLeadsRoute = SocialLeadsRouteImport.update({
  id: '/social-leads',
  path: '/social-leads',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveDemoRoute = LiveDemoRouteImport.update({
  id: '/live-demo',
  path: '/live-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveDashboardRoute = ExecutiveDashboardRouteImport.update({
  id: '/executive-dashboard',
  path: '/executive-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const BotFlowRoute = BotFlowRouteImport.update({
  id: '/bot-flow',
  path: '/bot-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSummaryRoute = AiSummaryRouteImport.update({
  id: '/ai-summary',
  path: '/ai-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const AiIntelligenceRoute = AiIntelligenceRouteImport.update({
  id: '/ai-intelligence',
  path: '/ai-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappFlowsIndexRoute = WhatsappFlowsIndexRouteImport.update({
  id: '/whatsapp-flows/',
  path: '/whatsapp-flows/',
  getParentRoute: () => rootRouteImport,
} as any)
const BotTreeIndexRoute = BotTreeIndexRouteImport.update({
  id: '/bot-tree/',
  path: '/bot-tree/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappFlowsNewRoute = WhatsappFlowsNewRouteImport.update({
  id: '/whatsapp-flows/new',
  path: '/whatsapp-flows/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappFlowsIdRoute = WhatsappFlowsIdRouteImport.update({
  id: '/whatsapp-flows/$id',
  path: '/whatsapp-flows/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowBuilderIdRoute = FlowBuilderIdRouteImport.update({
  id: '/flow-builder/$id',
  path: '/flow-builder/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BotTreeIdRoute = BotTreeIdRouteImport.update({
  id: '/bot-tree/$id',
  path: '/bot-tree/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-intelligence': typeof AiIntelligenceRoute
  '/ai-summary': typeof AiSummaryRoute
  '/automations': typeof AutomationsRoute
  '/bot-flow': typeof BotFlowRoute
  '/campaigns': typeof CampaignsRoute
  '/crm': typeof CrmRoute
  '/executive-dashboard': typeof ExecutiveDashboardRoute
  '/inbox': typeof InboxRoute
  '/live-demo': typeof LiveDemoRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/pricing': typeof PricingRoute
  '/social-leads': typeof SocialLeadsRoute
  '/team': typeof TeamRoute
  '/tammul': typeof TammulRoute
  '/bot-tree/$id': typeof BotTreeIdRoute
  '/flow-builder/$id': typeof FlowBuilderIdRoute
  '/whatsapp-flows/$id': typeof WhatsappFlowsIdRoute
  '/whatsapp-flows/new': typeof WhatsappFlowsNewRoute
  '/bot-tree/': typeof BotTreeIndexRoute
  '/whatsapp-flows/': typeof WhatsappFlowsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-intelligence': typeof AiIntelligenceRoute
  '/ai-summary': typeof AiSummaryRoute
  '/automations': typeof AutomationsRoute
  '/bot-flow': typeof BotFlowRoute
  '/campaigns': typeof CampaignsRoute
  '/crm': typeof CrmRoute
  '/executive-dashboard': typeof ExecutiveDashboardRoute
  '/inbox': typeof InboxRoute
  '/live-demo': typeof LiveDemoRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/pricing': typeof PricingRoute
  '/social-leads': typeof SocialLeadsRoute
  '/team': typeof TeamRoute
  '/tammul': typeof TammulRoute
  '/bot-tree/$id': typeof BotTreeIdRoute
  '/flow-builder/$id': typeof FlowBuilderIdRoute
  '/whatsapp-flows/$id': typeof WhatsappFlowsIdRoute
  '/whatsapp-flows/new': typeof WhatsappFlowsNewRoute
  '/bot-tree': typeof BotTreeIndexRoute
  '/whatsapp-flows': typeof WhatsappFlowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-intelligence': typeof AiIntelligenceRoute
  '/ai-summary': typeof AiSummaryRoute
  '/automations': typeof AutomationsRoute
  '/bot-flow': typeof BotFlowRoute
  '/campaigns': typeof CampaignsRoute
  '/crm': typeof CrmRoute
  '/executive-dashboard': typeof ExecutiveDashboardRoute
  '/inbox': typeof InboxRoute
  '/live-demo': typeof LiveDemoRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/pricing': typeof PricingRoute
  '/social-leads': typeof SocialLeadsRoute
  '/team': typeof TeamRoute
  '/tammul': typeof TammulRoute
  '/bot-tree/$id': typeof BotTreeIdRoute
  '/flow-builder/$id': typeof FlowBuilderIdRoute
  '/whatsapp-flows/$id': typeof WhatsappFlowsIdRoute
  '/whatsapp-flows/new': typeof WhatsappFlowsNewRoute
  '/bot-tree/': typeof BotTreeIndexRoute
  '/whatsapp-flows/': typeof WhatsappFlowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-intelligence'
    | '/ai-summary'
    | '/automations'
    | '/bot-flow'
    | '/campaigns'
    | '/crm'
    | '/executive-dashboard'
    | '/inbox'
    | '/live-demo'
    | '/login'
    | '/pipeline'
    | '/pricing'
    | '/social-leads'
    | '/team'
    | '/tammul'
    | '/bot-tree/$id'
    | '/flow-builder/$id'
    | '/whatsapp-flows/$id'
    | '/whatsapp-flows/new'
    | '/bot-tree/'
    | '/whatsapp-flows/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-intelligence'
    | '/ai-summary'
    | '/automations'
    | '/bot-flow'
    | '/campaigns'
    | '/crm'
    | '/executive-dashboard'
    | '/inbox'
    | '/live-demo'
    | '/login'
    | '/pipeline'
    | '/pricing'
    | '/social-leads'
    | '/team'
    | '/tammul'
    | '/bot-tree/$id'
    | '/flow-builder/$id'
    | '/whatsapp-flows/$id'
    | '/whatsapp-flows/new'
    | '/bot-tree'
    | '/whatsapp-flows'
  id:
    | '__root__'
    | '/'
    | '/ai-intelligence'
    | '/ai-summary'
    | '/automations'
    | '/bot-flow'
    | '/campaigns'
    | '/crm'
    | '/executive-dashboard'
    | '/inbox'
    | '/live-demo'
    | '/login'
    | '/pipeline'
    | '/pricing'
    | '/social-leads'
    | '/team'
    | '/tammul'
    | '/bot-tree/$id'
    | '/flow-builder/$id'
    | '/whatsapp-flows/$id'
    | '/whatsapp-flows/new'
    | '/bot-tree/'
    | '/whatsapp-flows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiIntelligenceRoute: typeof AiIntelligenceRoute
  AiSummaryRoute: typeof AiSummaryRoute
  AutomationsRoute: typeof AutomationsRoute
  BotFlowRoute: typeof BotFlowRoute
  CampaignsRoute: typeof CampaignsRoute
  CrmRoute: typeof CrmRoute
  ExecutiveDashboardRoute: typeof ExecutiveDashboardRoute
  InboxRoute: typeof InboxRoute
  LiveDemoRoute: typeof LiveDemoRoute
  LoginRoute: typeof LoginRoute
  PipelineRoute: typeof PipelineRoute
  PricingRoute: typeof PricingRoute
  SocialLeadsRoute: typeof SocialLeadsRoute
  TeamRoute: typeof TeamRoute
  TammulRoute: typeof TammulRoute
  BotTreeIdRoute: typeof BotTreeIdRoute
  FlowBuilderIdRoute: typeof FlowBuilderIdRoute
  WhatsappFlowsIdRoute: typeof WhatsappFlowsIdRoute
  WhatsappFlowsNewRoute: typeof WhatsappFlowsNewRoute
  BotTreeIndexRoute: typeof BotTreeIndexRoute
  WhatsappFlowsIndexRoute: typeof WhatsappFlowsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tammul': {
      id: '/tammul'
      path: '/tammul'
      fullPath: '/tammul'
      preLoaderRoute: typeof TammulRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-leads': {
      id: '/social-leads'
      path: '/social-leads'
      fullPath: '/social-leads'
      preLoaderRoute: typeof SocialLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-demo': {
      id: '/live-demo'
      path: '/live-demo'
      fullPath: '/live-demo'
      preLoaderRoute: typeof LiveDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive-dashboard': {
      id: '/executive-dashboard'
      path: '/executive-dashboard'
      fullPath: '/executive-dashboard'
      preLoaderRoute: typeof ExecutiveDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot-flow': {
      id: '/bot-flow'
      path: '/bot-flow'
      fullPath: '/bot-flow'
      preLoaderRoute: typeof BotFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-summary': {
      id: '/ai-summary'
      path: '/ai-summary'
      fullPath: '/ai-summary'
      preLoaderRoute: typeof AiSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-intelligence': {
      id: '/ai-intelligence'
      path: '/ai-intelligence'
      fullPath: '/ai-intelligence'
      preLoaderRoute: typeof AiIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp-flows/': {
      id: '/whatsapp-flows/'
      path: '/whatsapp-flows'
      fullPath: '/whatsapp-flows/'
      preLoaderRoute: typeof WhatsappFlowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot-tree/': {
      id: '/bot-tree/'
      path: '/bot-tree'
      fullPath: '/bot-tree/'
      preLoaderRoute: typeof BotTreeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp-flows/new': {
      id: '/whatsapp-flows/new'
      path: '/whatsapp-flows/new'
      fullPath: '/whatsapp-flows/new'
      preLoaderRoute: typeof WhatsappFlowsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp-flows/$id': {
      id: '/whatsapp-flows/$id'
      path: '/whatsapp-flows/$id'
      fullPath: '/whatsapp-flows/$id'
      preLoaderRoute: typeof WhatsappFlowsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow-builder/$id': {
      id: '/flow-builder/$id'
      path: '/flow-builder/$id'
      fullPath: '/flow-builder/$id'
      preLoaderRoute: typeof FlowBuilderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot-tree/$id': {
      id: '/bot-tree/$id'
      path: '/bot-tree/$id'
      fullPath: '/bot-tree/$id'
      preLoaderRoute: typeof BotTreeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiIntelligenceRoute: AiIntelligenceRoute,
  AiSummaryRoute: AiSummaryRoute,
  AutomationsRoute: AutomationsRoute,
  BotFlowRoute: BotFlowRoute,
  CampaignsRoute: CampaignsRoute,
  CrmRoute: CrmRoute,
  ExecutiveDashboardRoute: ExecutiveDashboardRoute,
  InboxRoute: InboxRoute,
  LiveDemoRoute: LiveDemoRoute,
  LoginRoute: LoginRoute,
  PipelineRoute: PipelineRoute,
  PricingRoute: PricingRoute,
  SocialLeadsRoute: SocialLeadsRoute,
  TeamRoute: TeamRoute,
  TammulRoute: TammulRoute,
  BotTreeIdRoute: BotTreeIdRoute,
  FlowBuilderIdRoute: FlowBuilderIdRoute,
  WhatsappFlowsIdRoute: WhatsappFlowsIdRoute,
  WhatsappFlowsNewRoute: WhatsappFlowsNewRoute,
  BotTreeIndexRoute: BotTreeIndexRoute,
  WhatsappFlowsIndexRoute: WhatsappFlowsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
