/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappFlowsRouteImport } from './routes/whatsapp-flows'
import { Route as TeamRouteImport } from './routes/team'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as ExecutiveDashboardRouteImport } from './routes/executive-dashboard'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as BotTreeRouteImport } from './routes/bot-tree'
import { Route as BotFlowRouteImport } from './routes/bot-flow'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as AiSummaryRouteImport } from './routes/ai-summary'
import { Route as AiIntelligenceRouteImport } from './routes/ai-intelligence'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WhatsappFlowsNewRouteImport } from './routes/whatsapp-flows.new'
import { Route as WhatsappFlowsIdRouteImport } from './routes/whatsapp-flows.$id'
import { Route as FlowBuilderIdRouteImport } from './routes/flow-builder.$id'
import { Route as BotTreeIdRouteImport } from './routes/bot-tree.$id'

const WhatsappFlowsRoute = WhatsappFlowsRouteImport.update({
  id: '/whatsapp-flows',
  path: '/whatsapp-flows',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveDashboardRoute = ExecutiveDashboardRouteImport.update({
  id: '/executive-dashboard',
  path: '/executive-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const BotTreeRoute = BotTreeRouteImport.update({
  id: '/bot-tree',
  path: '/bot-tree',
  getParentRoute: () => rootRouteImport,
} as any)
const BotFlowRoute = BotFlowRouteImport.update({
  id: '/bot-flow',
  path: '/bot-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSummaryRoute = AiSummaryRouteImport.update({
  id: '/ai-summary',
  path: '/ai-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const AiIntelligenceRoute = AiIntelligenceRouteImport.update({
  id: '/ai-intelligence',
  path: '/ai-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappFlowsNewRoute = WhatsappFlowsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => WhatsappFlowsRoute,
} as any)
const WhatsappFlowsIdRoute = WhatsappFlowsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WhatsappFlowsRoute,
} as any)
const FlowBuilderIdRoute = FlowBuilderIdRouteImport.update({
  id: '/flow-builder/$id',
  path: '/flow-builder/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BotTreeIdRoute = BotTreeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BotTreeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-intelligence': typeof AiIntelligenceRoute
  '/ai-summary': typeof AiSummaryRoute
  '/automations': typeof AutomationsRoute
  '/bot-flow': typeof BotFlowRoute
  '/bot-tree': typeof BotTreeRouteWithChildren
  '/campaigns': typeof CampaignsRoute
  '/crm': typeof CrmRoute
  '/executive-dashboard': typeof ExecutiveDashboardRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/team': typeof TeamRoute
  '/whatsapp-flows': typeof WhatsappFlowsRouteWithChildren
  '/bot-tree/$id': typeof BotTreeIdRoute
  '/flow-builder/$id': typeof FlowBuilderIdRoute
  '/whatsapp-flows/$id': typeof WhatsappFlowsIdRoute
  '/whatsapp-flows/new': typeof WhatsappFlowsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-intelligence': typeof AiIntelligenceRoute
  '/ai-summary': typeof AiSummaryRoute
  '/automations': typeof AutomationsRoute
  '/bot-flow': typeof BotFlowRoute
  '/bot-tree': typeof BotTreeRouteWithChildren
  '/campaigns': typeof CampaignsRoute
  '/crm': typeof CrmRoute
  '/executive-dashboard': typeof ExecutiveDashboardRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/team': typeof TeamRoute
  '/whatsapp-flows': typeof WhatsappFlowsRouteWithChildren
  '/bot-tree/$id': typeof BotTreeIdRoute
  '/flow-builder/$id': typeof FlowBuilderIdRoute
  '/whatsapp-flows/$id': typeof WhatsappFlowsIdRoute
  '/whatsapp-flows/new': typeof WhatsappFlowsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-intelligence': typeof AiIntelligenceRoute
  '/ai-summary': typeof AiSummaryRoute
  '/automations': typeof AutomationsRoute
  '/bot-flow': typeof BotFlowRoute
  '/bot-tree': typeof BotTreeRouteWithChildren
  '/campaigns': typeof CampaignsRoute
  '/crm': typeof CrmRoute
  '/executive-dashboard': typeof ExecutiveDashboardRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/team': typeof TeamRoute
  '/whatsapp-flows': typeof WhatsappFlowsRouteWithChildren
  '/bot-tree/$id': typeof BotTreeIdRoute
  '/flow-builder/$id': typeof FlowBuilderIdRoute
  '/whatsapp-flows/$id': typeof WhatsappFlowsIdRoute
  '/whatsapp-flows/new': typeof WhatsappFlowsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-intelligence'
    | '/ai-summary'
    | '/automations'
    | '/bot-flow'
    | '/bot-tree'
    | '/campaigns'
    | '/crm'
    | '/executive-dashboard'
    | '/inbox'
    | '/login'
    | '/pipeline'
    | '/team'
    | '/whatsapp-flows'
    | '/bot-tree/$id'
    | '/flow-builder/$id'
    | '/whatsapp-flows/$id'
    | '/whatsapp-flows/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-intelligence'
    | '/ai-summary'
    | '/automations'
    | '/bot-flow'
    | '/bot-tree'
    | '/campaigns'
    | '/crm'
    | '/executive-dashboard'
    | '/inbox'
    | '/login'
    | '/pipeline'
    | '/team'
    | '/whatsapp-flows'
    | '/bot-tree/$id'
    | '/flow-builder/$id'
    | '/whatsapp-flows/$id'
    | '/whatsapp-flows/new'
  id:
    | '__root__'
    | '/'
    | '/ai-intelligence'
    | '/ai-summary'
    | '/automations'
    | '/bot-flow'
    | '/bot-tree'
    | '/campaigns'
    | '/crm'
    | '/executive-dashboard'
    | '/inbox'
    | '/login'
    | '/pipeline'
    | '/team'
    | '/whatsapp-flows'
    | '/bot-tree/$id'
    | '/flow-builder/$id'
    | '/whatsapp-flows/$id'
    | '/whatsapp-flows/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiIntelligenceRoute: typeof AiIntelligenceRoute
  AiSummaryRoute: typeof AiSummaryRoute
  AutomationsRoute: typeof AutomationsRoute
  BotFlowRoute: typeof BotFlowRoute
  BotTreeRoute: typeof BotTreeRouteWithChildren
  CampaignsRoute: typeof CampaignsRoute
  CrmRoute: typeof CrmRoute
  ExecutiveDashboardRoute: typeof ExecutiveDashboardRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  PipelineRoute: typeof PipelineRoute
  TeamRoute: typeof TeamRoute
  WhatsappFlowsRoute: typeof WhatsappFlowsRouteWithChildren
  FlowBuilderIdRoute: typeof FlowBuilderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp-flows': {
      id: '/whatsapp-flows'
      path: '/whatsapp-flows'
      fullPath: '/whatsapp-flows'
      preLoaderRoute: typeof WhatsappFlowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive-dashboard': {
      id: '/executive-dashboard'
      path: '/executive-dashboard'
      fullPath: '/executive-dashboard'
      preLoaderRoute: typeof ExecutiveDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot-tree': {
      id: '/bot-tree'
      path: '/bot-tree'
      fullPath: '/bot-tree'
      preLoaderRoute: typeof BotTreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot-flow': {
      id: '/bot-flow'
      path: '/bot-flow'
      fullPath: '/bot-flow'
      preLoaderRoute: typeof BotFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-summary': {
      id: '/ai-summary'
      path: '/ai-summary'
      fullPath: '/ai-summary'
      preLoaderRoute: typeof AiSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-intelligence': {
      id: '/ai-intelligence'
      path: '/ai-intelligence'
      fullPath: '/ai-intelligence'
      preLoaderRoute: typeof AiIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp-flows/new': {
      id: '/whatsapp-flows/new'
      path: '/new'
      fullPath: '/whatsapp-flows/new'
      preLoaderRoute: typeof WhatsappFlowsNewRouteImport
      parentRoute: typeof WhatsappFlowsRoute
    }
    '/whatsapp-flows/$id': {
      id: '/whatsapp-flows/$id'
      path: '/$id'
      fullPath: '/whatsapp-flows/$id'
      preLoaderRoute: typeof WhatsappFlowsIdRouteImport
      parentRoute: typeof WhatsappFlowsRoute
    }
    '/flow-builder/$id': {
      id: '/flow-builder/$id'
      path: '/flow-builder/$id'
      fullPath: '/flow-builder/$id'
      preLoaderRoute: typeof FlowBuilderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot-tree/$id': {
      id: '/bot-tree/$id'
      path: '/$id'
      fullPath: '/bot-tree/$id'
      preLoaderRoute: typeof BotTreeIdRouteImport
      parentRoute: typeof BotTreeRoute
    }
  }
}

interface BotTreeRouteChildren {
  BotTreeIdRoute: typeof BotTreeIdRoute
}

const BotTreeRouteChildren: BotTreeRouteChildren = {
  BotTreeIdRoute: BotTreeIdRoute,
}

const BotTreeRouteWithChildren =
  BotTreeRoute._addFileChildren(BotTreeRouteChildren)

interface WhatsappFlowsRouteChildren {
  WhatsappFlowsIdRoute: typeof WhatsappFlowsIdRoute
  WhatsappFlowsNewRoute: typeof WhatsappFlowsNewRoute
}

const WhatsappFlowsRouteChildren: WhatsappFlowsRouteChildren = {
  WhatsappFlowsIdRoute: WhatsappFlowsIdRoute,
  WhatsappFlowsNewRoute: WhatsappFlowsNewRoute,
}

const WhatsappFlowsRouteWithChildren = WhatsappFlowsRoute._addFileChildren(
  WhatsappFlowsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiIntelligenceRoute: AiIntelligenceRoute,
  AiSummaryRoute: AiSummaryRoute,
  AutomationsRoute: AutomationsRoute,
  BotFlowRoute: BotFlowRoute,
  BotTreeRoute: BotTreeRouteWithChildren,
  CampaignsRoute: CampaignsRoute,
  CrmRoute: CrmRoute,
  ExecutiveDashboardRoute: ExecutiveDashboardRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  PipelineRoute: PipelineRoute,
  TeamRoute: TeamRoute,
  WhatsappFlowsRoute: WhatsappFlowsRouteWithChildren,
  FlowBuilderIdRoute: FlowBuilderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
