/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as ExecutiveDashboardRouteImport } from './routes/executive-dashboard'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as AiSummaryRouteImport } from './routes/ai-summary'
import { Route as AiIntelligenceRouteImport } from './routes/ai-intelligence'
import { Route as IndexRouteImport } from './routes/index'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveDashboardRoute = ExecutiveDashboardRouteImport.update({
  id: '/executive-dashboard',
  path: '/executive-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSummaryRoute = AiSummaryRouteImport.update({
  id: '/ai-summary',
  path: '/ai-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const AiIntelligenceRoute = AiIntelligenceRouteImport.update({
  id: '/ai-intelligence',
  path: '/ai-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-intelligence': typeof AiIntelligenceRoute
  '/ai-summary': typeof AiSummaryRoute
  '/automations': typeof AutomationsRoute
  '/campaigns': typeof CampaignsRoute
  '/crm': typeof CrmRoute
  '/executive-dashboard': typeof ExecutiveDashboardRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-intelligence': typeof AiIntelligenceRoute
  '/ai-summary': typeof AiSummaryRoute
  '/automations': typeof AutomationsRoute
  '/campaigns': typeof CampaignsRoute
  '/crm': typeof CrmRoute
  '/executive-dashboard': typeof ExecutiveDashboardRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-intelligence': typeof AiIntelligenceRoute
  '/ai-summary': typeof AiSummaryRoute
  '/automations': typeof AutomationsRoute
  '/bot-flow': typeof BotFlowRoute
  '/campaigns': typeof CampaignsRoute
  '/crm': typeof CrmRoute
  '/executive-dashboard': typeof ExecutiveDashboardRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/team': typeof TeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-intelligence'
    | '/ai-summary'
    | '/automations'
    | '/campaigns'
    | '/crm'
    | '/executive-dashboard'
    | '/inbox'
    | '/login'
    | '/pipeline'
    | '/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-intelligence'
    | '/ai-summary'
    | '/automations'
    | '/campaigns'
    | '/crm'
    | '/executive-dashboard'
    | '/inbox'
    | '/login'
    | '/pipeline'
    | '/team'
  id:
    | '__root__'
    | '/'
    | '/ai-intelligence'
    | '/ai-summary'
    | '/automations'
    | '/campaigns'
    | '/crm'
    | '/executive-dashboard'
    | '/inbox'
    | '/login'
    | '/pipeline'
    | '/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiIntelligenceRoute: typeof AiIntelligenceRoute
  AiSummaryRoute: typeof AiSummaryRoute
  AutomationsRoute: typeof AutomationsRoute
  CampaignsRoute: typeof CampaignsRoute
  CrmRoute: typeof CrmRoute
  ExecutiveDashboardRoute: typeof ExecutiveDashboardRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  PipelineRoute: typeof PipelineRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive-dashboard': {
      id: '/executive-dashboard'
      path: '/executive-dashboard'
      fullPath: '/executive-dashboard'
      preLoaderRoute: typeof ExecutiveDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-summary': {
      id: '/ai-summary'
      path: '/ai-summary'
      fullPath: '/ai-summary'
      preLoaderRoute: typeof AiSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-intelligence': {
      id: '/ai-intelligence'
      path: '/ai-intelligence'
      fullPath: '/ai-intelligence'
      preLoaderRoute: typeof AiIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiIntelligenceRoute: AiIntelligenceRoute,
  AiSummaryRoute: AiSummaryRoute,
  AutomationsRoute: AutomationsRoute,
  CampaignsRoute: CampaignsRoute,
  CrmRoute: CrmRoute,
  ExecutiveDashboardRoute: ExecutiveDashboardRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  PipelineRoute: PipelineRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
